name: Run Newman Tests

on:
  schedule:
    - cron: '0 9 * * *'  # Ejecutar cada día a las 9 AM
  push:
    branches:
      - qa
      - staging
  pull_request:
    branches:
      - qa
      - staging
  workflow_dispatch:
  
jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Newman and htmlextra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: List Files in Working Directory (Optional)
        run: ls -la

      - name: Run Newman tests with htmlextra reporter
        run: |
          newman "PlaceAnalyzer.postman_collection.json" --reporters htmlextra --reporter-htmlextra-export newman-report.html || true
        continue-on-error: true

      - name: List files after Newman run (Optional)
        run: ls -la

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: newman-htmlextra-report
          path: newman-report.html
          if-no-files-found: warn
